######################################################################
# Automatically generated by qmake (3.0) Sun Sep 11 18:26:07 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
SOURCES += \
    backuptest.cpp \
    ../src/backup.cpp \


HEADERS += \
    ../src/backup.h
